[package]
name = "kova-query"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "KQL : query language for Kova. Parser, binder, planner, executor."

[dependencies]
kova-core = { path = "../kova-core" }
kova-storage = { path = "../kova-storage" }
kova-meta-index = { path = "../kova-meta-index" }
roaring = "0.10"
thiserror.workspace = true
pest = "2"
pest_derive = "2"

[dev-dependencies]
kova-index = { path = "../kova-index" }
tempfile = "3"
rand = "0.10"

[lints]
workspace = true
